issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-forks/ingress-nginx:ref:refs/heads/main
claim_pattern:
  workflow_ref: chainguard-forks/ingress-nginx/.github/workflows/release.yml@refs/heads/main

permissions:
  contents: write
